### ISSUE TITLE
Green slime issue

### ISSUE THREAD

**Issue by lordhater1** [Ormael7/Corruption-of-Champions#107]
After I’ve beaten the Green Slime a certain number of times, in between rounds when we’re fighting, when I press the “Next” button, nothing happens, no matter how many times I press it. This issue has occurred 3 times for me now. If you could be able to look into this problem, I would greatly appreciate it.

**Comment by Ormael7** [comment]
According to Liadri it was fixed around time stats was refactored. Unless it happens again i will close it for now as solved.
