### ISSUE TITLE
Kitsune Thyroid Gland

### ISSUE THREAD

**Issue by Restkastel2** [Ormael7/Corruption-of-Champions#126]
It seems that the Kitsune Thyroid Gland perk is very bugged, as it causes your health to constantly go down as you have it. This doesn't seem to be intended as its not marked in the perk text, nor is it reflected in the heal amounts from rest, so I would imagine there is some sort of mixup in the code somewhere with regeneration amounts.

**Comment by Anon44d** [comment]
Every organ perk reduce regen by 0.5% Max HP(may lead to negative regen), probably that's the case.

**Comment by Ormael7** [comment]
Yes each racial mutation perk like Kitsune Thyroid Gland would give 0.5% max HP negative health regeneration. To counter this it's req. to pick some perk that give positive HP regeneration (like perks Regeneration) or choosing Chimera Body perks to lower negative regen effects.
