### ISSUE TITLE
Samirah, Yu and Diva

### ISSUE THREAD

**Issue by Anon44d** [Ormael7/Corruption-of-Champions#140]
Adobe Flash Player 23 / 0.8n8

1. Samirah using -name- instead of [name].
https://github.com/Ormael7/Corruption-of-Champions/blob/5d1d64915a5a755a5b51c5c8717df119e7478ad2/classes/classes/Scenes/NPCs/SamirahScene.as#L169

2. Yu sex with genderless lead to Error: Invalid vagina number (0) passed to vaginaDescript(). 

3. Any Diva sex scene doesn't lead to orgasm resulting in no lust relief, teasexp etc.

**Comment by Ormael7** [comment]
Liadri will handle Diva issue and i handles by now first 2 (for genderless put lock to make genderless ones not able to get sex options - I know most of the game getting hairwire when genderless pc try to have sex scenes)

**Comment by Ormael7** [comment]
All 3 issues solved.
