### ISSUE TITLE
Racial Paragon Issues in N8 and out

### ISSUE THREAD

**Issue by Lunaraia** [Ormael7/Corruption-of-Champions#151]
if you pick the Racial Paragon perk you get locked as human as the perk will immediately 0 ALL racial scores aside from Humanity and Internal Chimerical disposition, regardless of your current race. and the 2 racial scores you get when you pick your race are nowhere near enough to compensate for this.

**Comment by Liadri** [comment]
Likely long fixed I havent seen anything regarding this in a long time

**Comment by Ormael7** [comment]
Closing it then unless there will be new report on this issue.
