### ISSUE TITLE
"Ecliptic Mind" perk requires itself

### ISSUE THREAD

**Issue by elfapologist** [Ormael7/Corruption-of-Champions#158]
0.8n10

It is currently impossible to select any of the "Ecliptic Mind" perks as a unicorn/bicorn or alicorn/nightmare, as they all list themselves as a prerequisite.

https://github.com/Ormael7/Corruption-of-Champions/blob/797cc9ebb63a5cd946e05289d2a04c76db8f9e84/classes/classes/PerkLib.as#L5340

**Comment by Ormael7** [comment]
Issue solved.
