### ISSUE TITLE
Tripxi Guns variables getting printed in the Camp's Soulforce menu.

### ISSUE THREAD

**Issue by Stretop** [Ormael7/Corruption-of-Champions#205]
After the first discussion of small assortment of guns with Tripxi in TelAdre the Soulforce menu in the Camp gives this text:

Cultivation stage: Late Soul Apprentice
Cultivation level: 6
Additional Soulforce from training: 0 / 1430
TelAdre Tripxi Guns general timer: 4
TelAdre Tripxi Guns 1 (v1): 0 (Desert Eagle)
TelAdre Tripxi Guns 1 (v2): 0 (Dart pistol)
TelAdre Tripxi Guns 1 (v3): 0
TelAdre Tripxi Guns 1 (v4): 0
TelAdre Tripxi Guns 2 (v1): 0 (M1 Cerberus)
TelAdre Tripxi Guns 2 (v2): 0 (Twin Dart pistol)
TelAdre Tripxi Guns 2 (v3): 0
TelAdre Tripxi Guns 2 (v4): 0
TelAdre Tripxi Guns 3 (v1): 0 (Tripxi Fatbilly)
TelAdre Tripxi Guns 3 (v2): 0 (Harpoon Gun)
TelAdre Tripxi Guns 3 (v3): 0
TelAdre Tripxi Guns 3 (v4): 0
TelAdre Tripxi Guns 4 (v1): 0 (Snippler)
TelAdre Tripxi Guns 4 (v2): 0
TelAdre Tripxi Guns 4 (v3): 0
TelAdre Tripxi Guns 4 (v4): 0
TelAdre Tripxi Guns 5 (v1): 0 (Touhouna M3)
TelAdre Tripxi Guns 5 (v2): 2 (Derpnade Launcher)
TelAdre Tripxi Guns 5 (v3): 0
TelAdre Tripxi Guns 5 (v4): 0
TelAdre Tripxi Guns 6 (v1): 0 (Twin Grakaturd)
TelAdre Tripxi Guns 6 (v2): 0
TelAdre Tripxi Guns 6 (v3): 0
TelAdre Tripxi Guns 6 (v4): 0
Uses of soulforce per day (for 4 first option beside cultivate): 0 / 1

Steps to reproduce:
1) Go to Places > TelAdre > Shops > Gunsmith
2) Mention "small selection"
3) Go back to the camp
4) Press "Soulforce" button

Expexted behaviour: those "TelAdre Tripxi Guns" strings should not be printed there.

**Comment by Ormael7** [comment]
Removed printing those strings so the issue is solved now. My fault for it to show up thou so well more like i fixed my own mess up.
