### ISSUE TITLE
Hellcat to Kasha seems broken.

### ISSUE THREAD

**Issue by crealname** [Ormael7/Corruption-of-Champions#230]
I looked at the changelog and decided to go for an unarmed run, and when I got to full Hellcat TF I decided to try the Kasha TF. After consuming a few Ghastly Fruit, I got the twin tails but any amount of time passing afterward turns the PC back into a cat-morph, I confirmed that it was the tail's fault by using the debug menu to change it back to burning. I do not have only consumed Whisker Fruit and Ghastly Fruit as far as TFs go for this run so I don't think I did anything to cause this.

CoC Xianxia [1.0.2_mod_Xianxia_0.8o2]
PC Ver, Windows 10 Home

**Comment by Ormael7** [comment]
Fixed by Liadri.
