### ISSUE TITLE
Staff Channeling perk is broken

### ISSUE THREAD

**Issue by mrttao** [Ormael7/Corruption-of-Champions#419]
`Staff Channeling - Basic attack with wizard’s staff is replaced with ranged magic bolt. (Allow attack flying enemies)`
this perk does not work. basic attacks still perform a melee attack dealing damage based on physical abilities rather than using the basic magic bolt. There is also no place to toggle this, unlike other combat options

**Comment by Ormael7** [comment]
It's desc of perk been unclear. It allow to use melee attacks when pc is on the ground and enemy is flying. I adjusted today perk desc to be more correct to what it doing ingame.

**Comment by mrttao** [comment]
> It's desc of perk been unclear. It allow to use melee attacks when pc is on the ground and enemy is flying. I adjusted today perk desc to be more correct to what it doing ingame.

wait really? if the issue is that the description is misleading and it is working as intended then what exactly is it doing? you are "channeling magical energy through a wizard staff". which in turn somehow results in "you deal strength damage to flying enemies"? that does not really make sense.

It should really replace the basic attack button with a basic magic bolt button. It makes no sense right now, if you are not a wizard you are not going into battle with a wizard staff. If you are a wizard your strength attack sucks and you want to use your magic attack. You can already hit flying enemies with the basic magic bolt, and in fact it is utterly necessary to deal any damage to them. (20 dmg dealt vs 200,000 dmg dealt).

The perk exists solely as a perk tax for wizards who want to reduce the number of clicks they have to go through to perform a basic attack. It shouldn't even be a perk really, it should just be a default combat option has that lets them switch the basic attack button for basic magic bolt or basic qi blast.

I am baffled why staff channelling operation method was changed from UEE mod where it works by changing the [attack] button for the [M.Bolt] button. the same [M.Bolt] that is under Spells in both it and xianxia mod

**Comment by Ormael7** [comment]
You're correct in those thoughts. I made changes so if PC meet req. it will be replacoing basic melee attack button in combat menu with Magic/Elemental Bolt button. Still those that can attack enemies without need of staffs or partial staffs (dominika quest related spellblade or devil scythe) would still be using default melee attack button.

**Comment by mrttao** [comment]
thank you. this is great
