### ISSUE TITLE
Goblin Mech Cum Reservoir never empties

### ISSUE THREAD

**Issue by elfapologist** [Ormael7/Corruption-of-Champions#575]
0.8s3

The "Impregnator 1.0" and "Fucking machine" masturbation scenes do not empty the cum reservoir, so once you've harvested cum from 4 encounters, you can impregnate yourself over and over without needing to harvest cum ever again.

https://github.com/Ormael7/Corruption-of-Champions/blob/3c531b61f9be6cf2ce3048ccfdbfda8b93030c1c/classes/classes/Scenes/Masturbation.as#L2381

**Comment by Ormael7** [comment]
Fixed it. Would be out with next public build.
