### ISSUE TITLE
Standard attacks always fail against DriderIncubus - TaintedMind issue

### ISSUE THREAD

**Issue by LizardsGithub** [Ormael7/Corruption-of-Champions#80]
Issue:
When fighting the Drider Incubus in the Stronghold, normal attacks will always fail as if the player is affected by Tainted Mind, and can be performed indefinitely, without the screen updating.

The problem lies in Combat.as, line 616 (as of 0.8j2)

```AS3
public function basemeleeattacks():void {
   if (monster is DriderIncubus) {
           (monster as DriderIncubus).taintedMindAttackAttempt();
           return;
   }
```

No check is made for the Tainted Mind effect, and in addition, it does not call the required functions for this action to take effect properly due to the early return.

(partial) Solution:

The code can be altered as follows:
```AS3
public function basemeleeattacks():void {
	if (monster is DriderIncubus) {
		if (player.hasStatusEffect(StatusEffects.TaintedMind)){
			clearOutput();
			(monster as DriderIncubus).taintedMindAttackAttempt();
			enemyAI();
			return;
		}
	}
```

This will correctly check for the status effect, along with updating the combat log and letting the enemy respond, or have the combat end due to max lust, etc. 

There, posted in the right place now. Not that there's much else here. I guess people usually just e-mail? Well here it is anyway.

**Comment by LizardsGithub** [comment]
Also, Tainted Mind never expires because of a typo on line 3425 of Combat.as

```AS3
player.addStatusValue(StatusEffects.TaintedMind, 1, 1);
```
It should be 
```AS3
player.addStatusValue(StatusEffects.TaintedMind, 1, -1);
```
To properly decrement the counter. With both issues fixed, the fight seems to work as expected.

**Comment by Ormael7** [comment]
Both parts of issue fixed and will go live with public j2 ver.
