### ISSUE TITLE
Freeze issue

### ISSUE THREAD

**Issue by GameMasterPo** [Ormael7/Corruption-of-Champions#93]
I'm posting this here too because the creator of the apk told me to post it here so I am, I found a bug in the latest version that if you recruit the shieldmaiden go through the dungeon and everything and get done with it and leave the dungeon everything's fine until you get the basic leadership perk and it states the shieldmaidens no longer in your party because if you go to the Dungeon it says you do not have a party and if you go to your Camp recruit your Etna then try to go into battle it states the shield Maiden steps forward but once you hit the next button it freezes the game I don't know what's going on but can you please fix it this is for the Android app for phones don't know if it's a thing on the other versions but it is athing on the Android phone version so please fix this issue because it's kind of annoying to have to restart the entire app just to be able to fight again and I even had to delete a save file because of this bug so please put on a patch or fix it in the next update because I really want to continue playing the game without the shield Maiden and them because they help out in battles alot

**Comment by Ormael7** [comment]
Yes I found this issue source and removed it (was my goffines to make game keep mistake Neisa and Etna)
