### ISSUE TITLE
Goblin Issue

### ISSUE THREAD

**Issue by dnkru** [Ormael7/Corruption-of-Champions#94]
I found a bug in which when you manage to defeat a goblin your game is stuck on the next and you cannot progress.

**Comment by Ormael7** [comment]
Coould you tell a bit more about this bug? Does it happen with all types of goblins or some specific one type?

**Comment by dnkru** [comment]
It happens with all goblins that I face

**Comment by ReNardier** [comment]
hey dnkru, you should post your save through anonfile/volafile for ormael7 to take a look at to help and fix this issue

**Comment by KuuKarisma** [comment]
Any updates with this issue? I get it as well whenever I face any goblin

**Comment by Ormael7** [comment]
Fixed (by Liadri).
