### ISSUE TITLE
mantis body issues

### ISSUE THREAD

**Issue by kingman804** [Ormael7/Corruption-of-Champions#97]
hey i found a bug on mantis morph when using Blade Grass i only got wing, abdomen, leg, arm,
penis, and Oviposition that it

**Comment by Ormael7** [comment]
You should without much trouble get antennae, tail and chitin coverihng body. With those body parts you listed that all that mantis tf giving atm (there is no eye, ears, face, tongue or rear body parts specific for mantis)
