### ISSUE TITLE
Manticore Venom Issue

### ISSUE THREAD

**Issue by tempestnano** [Ormael7/Corruption-of-Champions#99]
With a manticore tail, when used in combat, the tail venom charges goes to approx -90,000 instead of zero. It seems to recharge as normal; though, it would take ages to get back to zero.

**Comment by Ormael7** [comment]
Hmm looks I see there is second manticore tail spike form 2nd mutation eprk that makes PC slip under radar for req. venom allowing to go into negative. I would fix it for n2 as only this make sense to go into negative with manticore spike attack.

**Comment by Ormael7** [comment]
I updated manticore spike with regard to multi shooting all for too low price on tooltip and gamre allowing due to that going into venom debt.
